version: "3"
services:
  pipeline:
    build: .
    image: pipeline:latest
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "external"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword", "--silent"]
      interval: 5s
    volumes:
      - pipeline-datavolume:/var/lib/mysql
volumes:
  pipeline-datavolume:
    external:
      name: external
