version: "3"
services:
  pipeline:
    build: .
    image: pipeline:latest
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "external"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword", "--silent"]
      interval: 5s
  test:
    build: .
    volumes:
      - ./libs:/usr/app/libs
      - ./tests:/usr/app/tests
    depends_on:
      - pipeline
    environment:
      TEST_COUCH_URL: http://${COUCH_ADMIN}:${COUCH_PASS}@couch:5984
      TEST_PG_URL: postgres://postgres:${PG_PASS}@postgres:5432
