version: "3"
services:
  pipeline:
    build: .
    image: doximity/python-engineer-data:latest
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "external"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword", "--silent"]
      interval: 5s
